name: Build Artifacts

on:
  workflow_dispatch:
  workflow_call:


env:
  CARGO_TERM_COLOR: always
    
jobs:
  publish:
    name: Build artifacts for ${{ matrix.os }}
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt install build-essential libssl-dev pkg-config libglib2.0-dev libgtk-3-dev
      - uses: taiki-e/cache-cargo-install-action@v1 # taiki-e/install-action@v2
        with:
          tool: cargo-packager
      - name: Build binaries
        env:
            CARGO_PACKAGER_SIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.CARGO_PACKAGER_SIGN_PRIVATE_KEY_PASSWORD }}
            CARGO_PACKAGER_SIGN_PRIVATE_KEY: ${{ secrets.CARGO_PACKAGER_SIGN_PRIVATE_KEY }}
        run: cargo packager --release --formats all -vvv
        
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-release
          path: target/release/fendapp_*