
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  
  
jobs:
  test:
    name: Test for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt install build-essential libssl-dev pkg-config libglib2.0-dev libgtk-3-dev
      - name: Formatting
        run: cargo fmt --all --check
      - name: Linting
        run: cargo clippy --all-targets --all-features
      - name: Check
        run: cargo check 
      - name: Tests
        run: cargo test 
