
name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  CARGO_TERM_COLOR: always
  FROM_REF: ${{ github.event.pull_request.base.sha || (!github.event.forced && ( github.event.before != '0000000000000000000000000000000000000000'  && github.event.before || github.sha )) || format('{0}~', github.sha) }}
  TO_REF: ${{ github.sha }}

jobs:
  test:
    name: Test for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt install build-essential libssl-dev pkg-config libglib2.0-dev libgtk-3-dev
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - run: python -m pip freeze --local
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: pre-commit validation
        run: pre-commit run --show-diff-on-failure --color=always
      - name: Formatting
        run: pre-commit run --show-diff-on-failure --color=always --hook-stage push fmt
      - name: Linting
        run: pre-commit run --show-diff-on-failure --color=always --hook-stage push clippy
      - name: Tests
        run: pre-commit run --show-diff-on-failure --color=always --hook-stage push test
