name: Publish

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      is_nightly:
        description: "Is nightly"
        required: false
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  upload-artifacts:
    uses: ./.github/workflows/build_artifacts.yml
    secrets:
      CARGO_PACKAGER_SIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.CARGO_PACKAGER_SIGN_PRIVATE_KEY_PASSWORD }}
      CARGO_PACKAGER_SIGN_PRIVATE_KEY: ${{ secrets.CARGO_PACKAGER_SIGN_PRIVATE_KEY }}
  publish:
    if: '!cancelled()'
    needs: upload-artifacts
    runs-on: ubuntu-latest

    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
    #   - uses: actions/checkout@v4
    #     with:
    #       # https://github.com/actions/checkout/issues/1471
    #       fetch-tags: false
      - uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          merge-multiple: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: ${{ github.event.inputs.is_nightly }}
          overwrite: true
          file_glob: true
          file: release-artifacts/*
          tag: ${{ github.ref }}
