name: Publish

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      is_nightly:
        description: "Is nightly"
        required: false
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  upload-artifacts:
    uses: ./.github/workflows/build_artifacts.yml
    secrets:
      CARGO_PACKAGER_SIGN_PRIVATE_KEY_PASSWORD: ${{ secrets.CARGO_PACKAGER_SIGN_PRIVATE_KEY_PASSWORD }}
      CARGO_PACKAGER_SIGN_PRIVATE_KEY: ${{ secrets.CARGO_PACKAGER_SIGN_PRIVATE_KEY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  publish:
    if: '!cancelled()'
    needs: upload-artifacts
    runs-on: ubuntu-latest

    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-tags: true
      - uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          merge-multiple: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: ${{ github.event.inputs.is_nightly }}
          overwrite: true
          file_glob: true
          file: release-artifacts/*
          tag: ${{ github.ref }}
      - run: REF=${{ github.ref_type == 'tag' && github.ref_name || github.sha }}; echo "VERSION=${REF#v}" >> $GITHUB_ENV
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
            environment: production
            release: ${{ env.VERSION }}
